### ISSUE TITLE
NFR1: Two Sitemaps per User

### ISSUE THREAD

**Issue by LoganB0021** [WSU-4110/Levin#15]
|NFR1: Two Sitemaps per User| 
|---| 
|**Goal:** Create restrictions on user data usage|
|**Stakeholders:** User|
|**Description:** System shall not let users save more than two site maps per account.|
|**Origin:** Meeting|
|**Version:** 1|
|**Date:** 09/16/2022|
|**Priority:** 2|

**Comment by ahmed7599** [comment]
This issue was not plausible due to the Tasdyque receiving no help with the backend, and I could not help because I spent all my time coding the frontend.
