### ISSUE TITLE
NFR3: Login to Save Sitemaps

### ISSUE THREAD

**Issue by LoganB0021** [WSU-4110/Levin#17]
|NFR3: Login to Save Sitemaps| 
|---| 
|**Goal:** Allow users to save what they create on Levin|
|**Stakeholders:** User|
|**Description:** Users must log in if they want to save their sitemaps. This allows the user to use the service before committing to creating an account.|
|**Origin:** Meeting|
|**Version:** 1|
|**Date:** 09/16/2022|
|**Priority:** 1|

**Comment by ahmed7599** [comment]
This issue was not plausible due to the Tasdyque receiving no help with the backend, and I could not help because I spent all my time coding the frontend.
