### ISSUE TITLE
FR15: Register Sitemaps to Account

### ISSUE THREAD

**Issue by tahmidfaiz** [WSU-4110/Levin#20]
|FR15: Register Sitemaps to Account|
|---|
|**Goal**: The users can save existing sitemaps to their account|
**Stakeholders:** Users|
| **Description:** Users will be able to login into their Levin account. Any new sitemaps the user creates, the user can save them onto their account and, therefore, will be able to access the sitemap in the future.|
| **Origin:** Created by the team during the Initial meeting on 9/16/22.|
| **Version:** 1.0|
|**Date:** 09/18/2022|
|  **Priority:** 1|

**Comment by ahmed7599** [comment]
This issue was not plausible due to the Tasdyque receiving no help with the backend, and I could not help because I spent all my time coding the frontend.
