### ISSUE TITLE
FR13: Save Sitemap

### ISSUE THREAD

**Issue by Angjelo154** [WSU-4110/Levin#9]
|FR13: Save Sitemap|
|---|
|**Goal**: This feature will allow the user to save their sitemap
**Stakeholders:** Users
| **Description:** Once the user has decided they would like to save their sitemap, they will have the option to save it for future works with this feature.|
| **Version:** 1.0  |
|**Date:** 09/16/2022
|  **Priority:** 2 |

**Comment by ahmed7599** [comment]
This issue was not plausible due to the Tasdyque receiving no help with the backend. I was not able to help because I spent all my time coding the frontend.
